### ISSUE TITLE
Issues with running failsafe with Windows 10

### ISSUE THREAD

**Issue by abdul-farhat** [jan-molak/npm-failsafe#4]
Hi!

Can't seem to get this to work with my Windows 10 machine. Works fine on my Linux box. 
Any ideas? Much appreciated.

Node/npm versions:

```
PS C:\Users\farhata\github\tutorial-from-scripts-to-serenity> node -v
v8.9.4
PS C:\Users\farhata\github\tutorial-from-scripts-to-serenity> npm -v
v5.6.0
```

```
C:\Users\farhata\github\tutorial-from-scripts-to-serenity> npm test

> tutorial-from-scripts-to-serenity@1.0.0 pretest C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> serenity update

info: Serenity BDD CLI jar file is up to date :-)

> tutorial-from-scripts-to-serenity@1.0.0 test C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> failsafe clean protractor report

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! Test failed.  See above for more details.
```

Package file:

```
\\...
 "scripts": {
    "clean": "rimraf target",
    "pretest": "serenity update",
    "report": "serenity run",
    "test": "failsafe clean protractor report",
    "preprotractor": "webdriver-manager update --standalone --versions.standalone 3.0.1",
    "protractor": "protractor ./protractor.conf.js"
  },
\\...

**Comment by abdul-farhat** [comment]
Had to:

just replace

```
spawn('npm', ...
```
by

```
spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ...
```
See https://github.com/nodejs/node-v0.x-archive/issues/5841

**Comment by jan-molak** [comment]
Cool, thanks for letting me know! Would you like to submit a PR fixing that? Thanks!

**Comment by kopa** [comment]
Hi Jan, we were also experiencing this bug in our team.
Is there an ETA for a release with that pull request incorporated?
Thanks for your great tools!

**Comment by jan-molak** [comment]
Thanks, glad you find them useful!

The latest build includes a fix that should sort it out for you. I don't have a way to test it on Windows 10 at the moment, so please give it a go and let me know if everything's OK?

Best,
Jan
